# This is a basic workflow to help you get started with Actions

name: gcp-monitor

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
  schedule:
    - cron: '0 23 * * 1,2,3,4,5'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "monitoring"
  monitoring:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/modules/cloud-asset-inventory/ruby/gcp_monitor/Gemfile
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.TERRAFORM_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1.1.1'

      # Runs a single command using the runners shell
      - name: Get the date
        id: get_date
        # 今日の日付　YYYY-MM-DD
        # モニタリングは平日しか走らないため、
        # 月曜の場合、三日前の日付を取得します
        # それ以外の場合、一日前の日付を取得します
        run: |
          PAST_DATE=$(date -d "1 day ago" '+%Y-%m-%d')
          echo "past_date=$PAST_DATE" >> $GITHUB_OUTPUT
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: search for all iam policies
        id: get_current_iam_policies
        run: |
          gcloud asset search-all-iam-policies --scope=projects/workload-idenity-federation --format=json | jq '.' > iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}.json
          echo "file_path=iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}.json" >> $GITHUB_OUTPUT
      - name: upload current iam policies file
        uses: actions/upload-artifact@v3
        with:
          name: iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}
          path: iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}.json
          retention-days: 7
      # Runs a set of commands using the runners shell
      # https://stackoverflow.com/a/74232400
      # https://github.com/github/docs/issues/21529
      - name: get previous iam policies file
        id: download
        uses: actions/download-artifact@v3
        with:
          name: iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}
          path: cloud-asset-inventory/workload-idenity-dederation
      - name: display downloaded files
        run: ls -R
        working-directory: cloud-asset-inventory/workload-idenity-dederation
      # - name: iam policies diff summary
      - name: search for all gcp resources
        id: get_resources_diff
        run: |
          RESOURCES_MONITOR_RESULT="$(gcloud asset search-all-resources \
            --scope=projects/workload-idenity-federation \
            --order-by="updateTime DESC, assetType" \
            --query="updateTime>=${{ steps.get_date.outputs.past_date }} OR createTime>=${{ steps.get_date.outputs.past_date }}" \
            --format="json(name, displayName, assetType, project, createTime, updateTime)")"
          echo "resources_diff=$RESOURCES_MONITOR_RESULT" >> GITHUB_OUTPUT
      - name: diff_processing
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          # なぜかcacheを使うとエラーになる
          bundler-cache: true
          working-directory: ${{ github.workspace }}/modules/cloud-asset-inventory/ruby/gcp_monitor
      - run: bundle exec ruby ${{ github.workspace }}/modules/cloud-asset-inventory/ruby/gcp_monitor/app.rb ${{ secrets.SLACK_WEBHOOK_URL_FOR_GCP_MONITOR }} ${{ steps.get_current_iam_policies.outputs.file_path }} ${{ steps.download.outputs.download-path }}/iam-policies-workload-idenity-federation-${{ steps.get_date.outputs.current_date }}.json ${{ steps.get_resources_diff.outputs.resources_diff }}
