name: key-rotation-validator

on:
  # triggerは key_rotation workflow
  workflow_dispatch:

jobs:
  key_rotation_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          # key_rotation workflowより更新されたTEMP SA KEYを利用してGCP認証を行う
          credentials_json: '${{ secrets.TEMP_SA_KEY_FOR_ROTATION_VALIDATION }}'
      - name: Display current time
        # 現在時刻を出力します。これを持って、key_rotation workflowより発火した
        # key_rotation_validator workflowが今回実行された本workflowは同じかどうかを確認します
        run: TZ=Asia/Tokyo echo "The current time is $(date)"
      - name: run gcloud command to validate the new sa key
        run: |
          TZ=Asia/Tokyo gcloud info
